name: Auto Update Files

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'  # 每天UTC时间0点运行

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true
        ref: main  # 明确指定要修改的分支

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Execute update script
      run: |
        pip install requests
        pip install geoip2
        python update_config.py
        
    - name: Commit and push
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        if git diff --staged --quiet; then
          echo "没有需要提交的更改"
        else
          git commit -m "Auto update: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
        fi
